#!/bin/sh
###############################################################################
###############################################################################
#
# Copyright (c) 2012, Eric Garver
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met: 
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer. 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution. 
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###############################################################################
###############################################################################

###############################################################################
#
# Continuously receives text by opening a socket via netcat then pipes
# the output to xclip. It will xclip to primary, secondary, and clipboard.
#

NC_ARGS="-l -p 12345"
XCLIP_ARGS="-l 0"

[ -n "$NC" ] || NC="`which nc`"
[ -n "$XCLIP" ] || XCLIP="`which xclip`"

if [ ! -e "$NC" ]; then
    echo "Could not execute \"$NC\""
    exit 1
fi
if [ ! -e "$XCLIP" ]; then
    echo "Could not execute \"$XCLIP\""
    exit 1
fi

while true; do
    "$NC" $NC_ARGS | "$XCLIP" -f $XCLIP_ARGS | "$XCLIP" -f $XCLIP_ARGS -sel pri | "$XCLIP" $XCLIP_ARGS -sel clip
done
